os: osx
language: node_js
matrix:
  include:
    - osx_image: xcode7.3
      node_js: "8"
    - osx_image: xcode7.3
      node_js: "10"

    - osx_image: xcode8.3
      node_js: "8"
    - osx_image: xcode8.3
      node_js: "10"

    - osx_image: xcode9.4
      node_js: "8"
    - osx_image: xcode9.4
      node_js: "10"

    - osx_image: xcode10
      node_js: "8"
    - osx_image: xcode10
      node_js: "10"
script:
  - _FORCE_LOGS=1 npm test
after_success:
    - npm run coverage
