os: osx
language: node_js
node_js: "8"
matrix:
  include:
    - osx_image: xcode7.3
    - osx_image: xcode8.3
    - osx_image: xcode9.4
    - osx_image: xcode10.2
script:
  - _FORCE_LOGS=1 npm test
after_success:
    - npm run coverage
