os: osx
language: node_js
node_js: "10"
matrix:
  include:
    - osx_image: xcode7.3
    - osx_image: xcode7.3
      node_js: "12"

    - osx_image: xcode8.3
    - osx_image: xcode8.3
      node_js: "12"

    - osx_image: xcode9.4
    - osx_image: xcode9.4
      node_js: "12"

    - osx_image: xcode10.2
    - osx_image: xcode10.2
      node_js: "12"
script:
  - _FORCE_LOGS=1 npm test
after_success:
    - npm run coverage
