name: Node.js CI
on: [push, pull_request]
env:
  NODE_VERSION: 16.x

jobs:
  build:

    runs-on: macos-11

    strategy:
      matrix:
        xcode-version: ["11.7", "12.4", "13.2"]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: Select Xcode ${{ matrix.xcode-version }}
      run: sudo xcode-select --switch /Applications/Xcode_${{ matrix.xcode-version }}.app
    - run: npm run clean
    - run: _FORCE_LOGS=1 npm run test
